// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layouts/base.templ`, Line: 9, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " | EzWeb</title><link rel=\"icon\" href=\"data:,\"><link rel=\"stylesheet\" href=\"/static/css/tailwind.css?v=9\"><link rel=\"stylesheet\" href=\"/static/css/app.css?v=9\"><script defer src=\"/static/js/alpine.min.js\"></script><script src=\"/static/js/htmx.min.js\"></script></head><body class=\"bg-gray-50 min-h-screen antialiased\" hx-boost=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Keyboard shortcuts overlay --><div id=\"shortcuts-overlay\"><div class=\"shortcuts-panel\"><div class=\"flex justify-between items-center mb-4\"><h3 class=\"text-lg font-semibold\">Keyboard Shortcuts</h3><button data-close-overlay=\"shortcuts-overlay\" class=\"text-gray-400 hover:text-gray-600\">&times;</button></div><div class=\"space-y-3 text-sm\"><div class=\"flex justify-between\"><span>Show shortcuts</span><kbd>?</kbd></div><div class=\"flex justify-between\"><span>Dashboard</span><span><kbd>g</kbd> then <kbd>d</kbd></span></div><div class=\"flex justify-between\"><span>Sites</span><span><kbd>g</kbd> then <kbd>s</kbd></span></div><div class=\"flex justify-between\"><span>Customers</span><span><kbd>g</kbd> then <kbd>c</kbd></span></div><div class=\"flex justify-between\"><span>Payments</span><span><kbd>g</kbd> then <kbd>p</kbd></span></div><div class=\"flex justify-between\"><span>Servers</span><span><kbd>g</kbd> then <kbd>v</kbd></span></div><div class=\"flex justify-between\"><span>Backups</span><span><kbd>g</kbd> then <kbd>b</kbd></span></div><div class=\"flex justify-between\"><span>Close modal</span><kbd>Esc</kbd></div></div></div></div><script>\n\t\tdocument.body.addEventListener('htmx:configRequest', function(evt) {\n\t\t\tvar c = document.cookie.split('; ').find(function(c) { return c.startsWith('csrf_token='); });\n\t\t\tif (c) evt.detail.headers['X-CSRF-Token'] = c.split('=')[1];\n\t\t});\n\t\t</script><script src=\"/static/js/app.js?v=9\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
