package quote

import (
	"bytes"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"ezweb/internal/models"

	"github.com/go-pdf/fpdf"
)

// pageWidth is the usable width of a Letter page with 15mm margins on each side.
// Letter = 215.9mm wide; 215.9 - 30 = 185.9mm usable.
const pageWidth = 185.9

// GeneratePDF produces a PDF representation of the supplied quote and returns
// it as a byte slice ready for delivery over HTTP or storage to disk.
func GeneratePDF(db *sql.DB, q *models.Quote) ([]byte, error) {
	// --- load business settings ---
	bizName := models.GetSetting(db, "business_name")
	bizEmail := models.GetSetting(db, "email")
	bizPhone := models.GetSetting(db, "phone")
	bizAddress := models.GetSetting(db, "address")
	bizWebsite := models.GetSetting(db, "website_url")
	logoPath := models.GetSetting(db, "logo_path")
	termsText := models.GetSetting(db, "terms_text")

	pdf := fpdf.New("P", "mm", "Letter", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AliasNbPages("{nb}")

	// --- footer (page number + generator credit) ---
	footerBizName := bizName
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Arial", "I", 8)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(pageWidth/2, 5, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "L", false, 0, "")
		credit := "Generated by " + footerBizName
		if footerBizName == "" {
			credit = "Generated by EzWeb"
		}
		pdf.CellFormat(pageWidth/2, 5, credit, "", 0, "R", false, 0, "")
	})

	pdf.AddPage()

	// =========================================================================
	// HEADER — logo (right) + business info (left)
	// =========================================================================
	headerY := pdf.GetY()

	// Logo — attempt to load if path is set and file exists
	logoWidth := 0.0
	if logoPath != "" {
		absLogo := filepath.Join(".", logoPath)
		if _, statErr := os.Stat(absLogo); statErr == nil {
			logoWidth = 40.0
			logoX := 15.0 + pageWidth - logoWidth
			pdf.ImageOptions(absLogo, logoX, headerY, logoWidth, 0, false, fpdf.ImageOptions{ReadDpi: true}, 0, "")
		}
	}

	// Business name
	textBlockWidth := pageWidth - logoWidth - (5 * boolToFloat(logoWidth > 0))
	pdf.SetXY(15, headerY)
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	nameDisplay := bizName
	if nameDisplay == "" {
		nameDisplay = "Your Business"
	}
	pdf.CellFormat(textBlockWidth, 10, nameDisplay, "", 1, "L", false, 0, "")

	// Business contact lines
	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(80, 80, 80)
	for _, line := range contactLines(bizEmail, bizPhone, bizAddress, bizWebsite) {
		pdf.SetX(15)
		pdf.CellFormat(textBlockWidth, 5, line, "", 1, "L", false, 0, "")
	}

	// Ensure we advance past the logo height too
	afterHeader := pdf.GetY()
	if logoWidth > 0 {
		// Move down if logo is taller than the text block
		logoInfo := pdf.GetImageInfo(filepath.Join(".", logoPath))
		if logoInfo != nil {
			logoRenderedH := logoWidth * logoInfo.Height() / logoInfo.Width()
			candidateY := headerY + logoRenderedH + 2
			if candidateY > afterHeader {
				pdf.SetY(candidateY)
			}
		}
	}

	// Horizontal rule
	pdf.Ln(4)
	drawHRule(pdf, 0.4, 180, 180, 180)
	pdf.Ln(5)

	// =========================================================================
	// QUOTE INFO SECTION
	// =========================================================================
	quoteY := pdf.GetY()

	// "QUOTE" banner on the left
	pdf.SetFont("Arial", "B", 28)
	pdf.SetTextColor(40, 80, 160)
	pdf.CellFormat(pageWidth/2, 12, "QUOTE", "", 0, "L", false, 0, "")

	// Quote meta on the right
	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(60, 60, 60)
	pdf.SetXY(15+pageWidth/2, quoteY)

	metaRightW := pageWidth / 2
	labelW := 30.0
	valueW := metaRightW - labelW

	metaRow(pdf, 15+pageWidth/2, labelW, valueW, "Quote #:", shortenID(q.PublicID))
	metaRow(pdf, 15+pageWidth/2, labelW, valueW, "Date:", q.CreatedAt.Format("January 2, 2006"))
	if q.ValidUntil != "" {
		if t, err := time.Parse("2006-01-02", q.ValidUntil); err == nil {
			metaRow(pdf, 15+pageWidth/2, labelW, valueW, "Valid Until:", t.Format("January 2, 2006"))
		} else {
			metaRow(pdf, 15+pageWidth/2, labelW, valueW, "Valid Until:", q.ValidUntil)
		}
	}
	metaRow(pdf, 15+pageWidth/2, labelW, valueW, "Status:", strings.ToUpper(q.Status))

	// Move past whichever column is taller
	pdf.Ln(6)

	// =========================================================================
	// CLIENT INFO SECTION
	// =========================================================================
	sectionHeader(pdf, "Prepared For")

	pdf.SetFont("Arial", "B", 10)
	pdf.SetTextColor(30, 30, 30)
	pdf.SetX(15)
	pdf.CellFormat(pageWidth, 6, q.CustomerName, "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(80, 80, 80)
	for _, cl := range contactLines(q.CustomerEmail, q.CustomerPhone, "", "") {
		pdf.SetX(15)
		pdf.CellFormat(pageWidth, 5, cl, "", 1, "L", false, 0, "")
	}
	if q.CustomerCompany != "" {
		pdf.SetX(15)
		pdf.CellFormat(pageWidth, 5, q.CustomerCompany, "", 1, "L", false, 0, "")
	}

	pdf.Ln(6)

	// =========================================================================
	// LINE ITEMS TABLE
	// =========================================================================
	sectionHeader(pdf, "Line Items")

	// Column widths: item | description | amount
	colItem := 50.0
	colDesc := pageWidth - colItem - 35.0
	colAmt := 35.0

	// Table header row
	pdf.SetFont("Arial", "B", 9)
	pdf.SetFillColor(40, 80, 160)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetX(15)
	pdf.CellFormat(colItem, 7, "Item", "0", 0, "L", true, 0, "")
	pdf.CellFormat(colDesc, 7, "Description", "0", 0, "L", true, 0, "")
	pdf.CellFormat(colAmt, 7, "Amount", "0", 1, "R", true, 0, "")

	// Build line item rows
	type lineItem struct {
		item string
		desc string
		amt  float64
	}

	var items []lineItem

	// Setup fee
	if q.SetupFee > 0 || q.TemplateName != "" || q.TemplateSlug != "" {
		label := q.TemplateName
		if label == "" {
			label = q.TemplateSlug
		}
		if label == "" {
			label = "Setup"
		}
		items = append(items, lineItem{
			item: label,
			desc: "One-time setup fee",
			amt:  q.SetupFee,
		})
	}

	// Recurring price
	if q.BillingCycle == "yearly" && q.YearlyPrice > 0 {
		items = append(items, lineItem{
			item: "Hosting (Yearly)",
			desc: "Annual recurring plan",
			amt:  q.YearlyPrice,
		})
	} else if q.MonthlyPrice > 0 {
		items = append(items, lineItem{
			item: "Hosting (Monthly)",
			desc: "Monthly recurring plan",
			amt:  q.MonthlyPrice,
		})
	}

	// Domain registration
	if q.DomainName != "" {
		desc := "Domain registration"
		if q.DomainRegistrar != "" {
			desc = "Domain via " + q.DomainRegistrar
		}
		items = append(items, lineItem{
			item: q.DomainName,
			desc: desc,
			amt:  q.DomainPrice,
		})
	}

	// Addons
	for _, addon := range q.Addons {
		name := addon.AddonName
		if name == "" {
			name = fmt.Sprintf("Addon #%d", addon.AddonID)
		}
		desc := addon.PriceType
		if addon.Quantity > 1 {
			desc = fmt.Sprintf("x%d @ $%.2f each (%s)", addon.Quantity, addon.Price, addon.PriceType)
		}
		total := addon.Price * float64(addon.Quantity)
		items = append(items, lineItem{item: name, desc: desc, amt: total})
	}

	// Render rows with alternating fill
	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(30, 30, 30)
	for i, li := range items {
		if i%2 == 0 {
			pdf.SetFillColor(245, 247, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		pdf.SetX(15)
		pdf.CellFormat(colItem, 7, li.item, "0", 0, "L", true, 0, "")
		pdf.CellFormat(colDesc, 7, li.desc, "0", 0, "L", true, 0, "")
		pdf.CellFormat(colAmt, 7, formatMoney(li.amt), "0", 1, "R", true, 0, "")
	}

	// Bottom rule for table
	pdf.SetFillColor(255, 255, 255)
	pdf.Ln(2)
	drawHRule(pdf, 0.3, 200, 200, 200)
	pdf.Ln(5)

	// =========================================================================
	// TOTALS SECTION (right-aligned block)
	// =========================================================================
	totalsLabelW := 45.0
	totalsValueW := 35.0
	totalsX := 15.0 + pageWidth - totalsLabelW - totalsValueW

	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(60, 60, 60)

	totalsRow(pdf, totalsX, totalsLabelW, totalsValueW, "Subtotal:", formatMoney(q.Subtotal), false)

	if q.DiscountPercent > 0 {
		discountLabel := fmt.Sprintf("Discount (%.0f%%):", q.DiscountPercent)
		discountAmt := q.Subtotal * (q.DiscountPercent / 100)
		totalsRow(pdf, totalsX, totalsLabelW, totalsValueW, discountLabel, "-"+formatMoney(discountAmt), false)
	}

	if q.TaxRate > 0 {
		taxLabel := fmt.Sprintf("Tax (%.1f%%):", q.TaxRate)
		totalsRow(pdf, totalsX, totalsLabelW, totalsValueW, taxLabel, formatMoney(q.TaxAmount), false)
	}

	// Total row — bold, accented
	pdf.SetFont("Arial", "B", 11)
	pdf.SetTextColor(40, 80, 160)
	totalsRow(pdf, totalsX, totalsLabelW, totalsValueW, "Total:", formatMoney(q.Total), true)

	pdf.Ln(8)

	// =========================================================================
	// NOTES SECTION
	// =========================================================================
	if strings.TrimSpace(q.Notes) != "" {
		sectionHeader(pdf, "Notes")
		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(60, 60, 60)
		pdf.SetX(15)
		pdf.MultiCell(pageWidth, 5, q.Notes, "", "L", false)
		pdf.Ln(6)
	}

	// =========================================================================
	// TERMS SECTION
	// =========================================================================
	if strings.TrimSpace(termsText) != "" {
		sectionHeader(pdf, "Terms & Conditions")
		pdf.SetFont("Arial", "", 8)
		pdf.SetTextColor(100, 100, 100)
		pdf.SetX(15)
		pdf.MultiCell(pageWidth, 4.5, termsText, "", "L", false)
	}

	// --- render to bytes ---
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}
	return buf.Bytes(), nil
}

// ============================================================================
// helpers
// ============================================================================

// formatMoney formats a float as a dollar amount string, e.g. "$1,234.56".
func formatMoney(v float64) string {
	return fmt.Sprintf("$%.2f", v)
}

// shortenID returns the first segment of a UUID (before the first dash) for
// compact display, e.g. "a1b2c3d4" from "a1b2c3d4-...".
func shortenID(id string) string {
	if idx := strings.Index(id, "-"); idx != -1 {
		return strings.ToUpper(id[:idx])
	}
	if len(id) > 8 {
		return strings.ToUpper(id[:8])
	}
	return strings.ToUpper(id)
}

// contactLines assembles non-empty contact fields into a slice of display strings.
func contactLines(email, phone, address, website string) []string {
	var parts []string
	if email != "" {
		parts = append(parts, email)
	}
	if phone != "" {
		parts = append(parts, phone)
	}
	if address != "" {
		parts = append(parts, address)
	}
	if website != "" {
		parts = append(parts, website)
	}
	return parts
}

// sectionHeader renders a bold section title with a colored underline rule.
func sectionHeader(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Arial", "B", 10)
	pdf.SetTextColor(40, 80, 160)
	pdf.SetX(15)
	pdf.CellFormat(pageWidth, 6, strings.ToUpper(title), "", 1, "L", false, 0, "")
	drawHRule(pdf, 0.3, 40, 80, 160)
	pdf.Ln(3)
}

// drawHRule draws a full-width horizontal line in the given RGB color.
func drawHRule(pdf *fpdf.Fpdf, thickness float64, r, g, b int) {
	pdf.SetDrawColor(r, g, b)
	pdf.SetLineWidth(thickness)
	y := pdf.GetY()
	pdf.Line(15, y, 15+pageWidth, y)
	pdf.Ln(1)
}

// metaRow renders a label+value pair at a fixed X position, advancing Y only
// in the right-hand column.
func metaRow(pdf *fpdf.Fpdf, startX, labelW, valueW float64, label, value string) {
	pdf.SetX(startX)
	pdf.SetFont("Arial", "B", 9)
	pdf.SetTextColor(80, 80, 80)
	pdf.CellFormat(labelW, 5, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(valueW, 5, value, "", 1, "L", false, 0, "")
}

// totalsRow renders a label+value pair right-aligned in the totals block.
// When highlight is true it uses a light fill to visually emphasize the row.
func totalsRow(pdf *fpdf.Fpdf, startX, labelW, valueW float64, label, value string, highlight bool) {
	if highlight {
		pdf.SetFillColor(235, 241, 255)
		pdf.SetX(startX)
		pdf.CellFormat(labelW, 7, label, "0", 0, "R", true, 0, "")
		pdf.CellFormat(valueW, 7, value, "0", 1, "R", true, 0, "")
		pdf.SetFillColor(255, 255, 255)
	} else {
		pdf.SetX(startX)
		pdf.CellFormat(labelW, 6, label, "0", 0, "R", false, 0, "")
		pdf.CellFormat(valueW, 6, value, "0", 1, "R", false, 0, "")
	}
}

// boolToFloat converts a boolean condition to 1.0 or 0.0 for arithmetic use.
func boolToFloat(b bool) float64 {
	if b {
		return 1.0
	}
	return 0.0
}
